language: node_js
node_js:
  - "lts/*"
addons:
  sauce_connect: true
install:
  - npm install -g nightwatch
  - npm install
script:
  - nightwatch --config nightwatch.js
notifications:
  email:
    recipients:
      - joeriv@gmail.com
      - k.j.van.der.velde@umcg.nl
    on_success: always
    on_failure: always
